version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.16.5
    working_directory: /go/src/github.com/remove-bg/removebg
    steps:
      - checkout
      - run: echo 'export PATH=$GOPATH/bin:$PATH' >> "$BASH_ENV"
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - run: bin/setup
      - run: bin/test
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor

workflows:
  version: 2
  build:
    jobs:
      - build
