version: 2.1
orbs:
  gor: hubci/goreleaser@1.0.0
  go: circleci/go@1.7.0

workflows:
  main:
    jobs:
      - test
  release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - gor/release:
          version: 0.147.1
          go-version: 1.16.5
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
jobs:
  test:
    executor:
      name: go/default
      tag: '1.16.5'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache      
      - go/test

